jaffle_shop:
  outputs:
    dev:
      dataset: jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: coe-landing-zone-18-ats-2246
      threads: 1
      type: bigquery
  target: dev
