jaffle_shop:
  outputs:
    dev:
      dataset: jaffle_shop
      job_execution_timeout_seconds: 3000
      job_retries: 1
      location: US
      method: service-account
      priority: interactive
      project: coe-landing-zone-18-ats-2246
      threads: 4
      keyfile: /secrets/dbt-service-keyfile
      type: bigquery
  target: dev
