apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: test-api
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      hostNetwork: true
      containers:
      - name: hello-world-app
        image: hello-world
        ports:
          - containerPort: 8000
