apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      hostNetwork: true
      containers:
      - name: hello-world-app
        image: us-east1-docker.pkg.dev/coe-landing-zone-18-ats-2246/gke-cicd-repo/hello-world:<tag>
        #image: <image_repo>:<tag>
        ports:
          - containerPort: 8000
