apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: test-api
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8000":"backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
  selector:
    app: hello-world-app

